---
title: Oloren Homepage
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
    permalink: /blog/:title.html
  uploads:
    title: Uploads
    output: true
url: ''
baseurl: ''
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
plugins:
- jekyll-toc
