---
title: Oloren Blog Site
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
url: ''
baseurl: ''
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
plugins:
- jekyll-toc
